spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    #    prefix: classpath:/templates/
    prefix: file:src/main/resources/templates/
    #    prefix: ${project.basedir}/src/main/resources/templates/
    suffix: .html
    # excluded-view-names:
    # template-resolver-order:
    # view-names:
    servlet:
      content-type: text/html
server:
  port: 8081

logging:
  level:
    root: info
